version: '3.1'
services:

  stats-server:
    build: stats/server
    image: stats-image
    container_name: stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring_datasource_url=jdbc:postgresql://stats-db:5432/stats-db
      - spring.datasource.user=postgres
      - spring.datasource.password=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm
    image: ewm-image
    container_name: ewm-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - spring_datasource_url=jdbc:postgresql://ewm-db:5432/ewm-db
      - stats-server.url=http://stats-server:9090
      - spring.datasource.user=postgres
      - spring.datasource.password=postgres

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6541:6541"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres