DROP TABLE IF EXISTS public.hits CASCADE;

CREATE TABLE IF NOT EXISTS hits(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app         TEXT,
    uri         TEXT,
    ip          TEXT,
    time_stamp  TIMESTAMP WITHOUT TIME ZONE
);