DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.compilations CASCADE;
DROP TABLE IF EXISTS public.compilations_events CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.requests CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE IF NOT EXISTS users(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT,
    email TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS categories(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS locations(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT,
    lon FLOAT
);

CREATE TABLE IF NOT EXISTS events(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id       BIGINT REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    category_id        BIGINT REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE,
    location_id        BIGINT REFERENCES locations(id) ON DELETE CASCADE ON UPDATE CASCADE,
    title              TEXT,
    annotation         TEXT,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    paid               BOOLEAN,
    description        TEXT,
    confirmed_requests BIGINT,
    participant_limit  BIGINT,
    request_moderation BOOLEAN,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    state              TEXT,
    views              BIGINT
);

CREATE TABLE IF NOT EXISTS requests(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT REFERENCES events(id) ON DELETE CASCADE ON UPDATE CASCADE,
    requester_id    BIGINT REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    request_status  TEXT,
    created         TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS compilations(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned  BOOLEAN,
    title   TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations_events(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE ON UPDATE CASCADE,
    event_id       BIGINT REFERENCES events(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS comments(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES users(id),
    event_id        BIGINT REFERENCES events(id),
    text            TEXT,
    created_time    TIMESTAMP WITHOUT TIME ZONE,
    status          TEXT
);
